name: Build and Release PDF

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xu-cheng/texlive-full:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build PDF
        run: |
          mkdir -p build
          latexmk -pdf -outdir=build main.tex
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: build/main.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: main.pdf
          path: .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: main.pdf